### ISSUE TITLE
Update rpb lookuptables

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lookup-tables#61]
> Also there are 26 records that have are not part of the NZ but are in the rpb collection.

https://lobid.org/resources/search?q=inCollection.id%3A%22http%3A%2F%2Flobid.org%2Fresources%2FHT013494180%23%21%22+AND+NOT+inCollection.id%3A%22http%3A%2F%2Flobid.org%2Forganisations%2FDE-655%23%21%22

These seems mainly to be wrong mappings assigning records to CZ Consor Records instead of ZDB/NZ Records (21 instances). These can easily be fixed:

```
---
almaMmsId: "99370691768806441" (CZ Titel statt NZ ZDB)
rpbId: "929t01024538" -> HT015612364 -> 990170549260206441

---
almaMmsId: "99370695565206441" (CZ Titel statt NZ ZDB)
rpbId: "929t01074757" ->  HT017735962 -> 990197983170206441

---
almaMmsId: "99370695975906441" (CZ Titel statt NZ ZDB)
rpbId: "929t01041072" -> HT016926066 -> 990188172110206441

---
almaMmsId: "99370696004506441" (CZ Titel statt NZ ZDB)
rpbId: "929t01040576" -> HT017379813 -> 990192906610206441

---
almaMmsId: "99370685222206441" (CZ Titel statt NZ ZDB)
rpbId: "929t01076749" -> HT019971887 -> 990227800790206441

---
almaMmsId: "99370686223506441" (CZ Titel statt NZ ZDB)
rpbId: "929t01024509" -> HT015817615 -> 990173331820206441

---
almaMmsId: "99370686223106441" (CZ Titel statt NZ ZDB)
rpbId: "929t01034047" -> HT016225491 -> 990178421190206441

---
almaMmsId: "99370688114906441" (CZ Titel statt NZ ZDB)
rpbId: "929t01034103" -> HT016306054 -> 990179419420206441

---
almaMmsId: "99370698952906441" (CZ Titel statt NZ ZDB)
rpbId: "107t081447" -> HT015495978 -> 990165399670206441

---
almaMmsId: "99370686737106441" (CZ Titel statt NZ ZDB)
rpbId: "929t01024554" -> HT015817675 -> 990173332420206441

---
almaMmsId: "99370688948206441" (CZ Titel statt NZ ZDB)
rpbId: "929t01076258" -> HT019149553 -> 990214114060206441

---
almaMmsId: "99370683064406441" (CZ Titel statt NZ ZDB)
rpbId: "929t01024500" -> HT015941280 -> 990174711090206441

---
almaMmsId: "99370683584806441" (CZ Titel statt NZ ZDB)
rpbId: "929t01044786" -> HT016965533 -> 990188584160206441

---
almaMmsId: "99370685807106441" (CZ Titel statt NZ ZDB)
rpbId: "929t01076681" -> HT014169524 -> 990133002700206441

---
almaMmsId: "99370685802706441" (CZ Titel statt NZ ZDB)
rpbId: "929t01038384" -> HT016490325 -> 990181886860206441

---
almaMmsId: "99370696006406441" (CZ Titel statt NZ ZDB)
rpbId: "929t01040707" -> HT017446139 -> 990193588700206441

---
almaMmsId: "99370688470706441" (CZ Titel statt NZ ZDB)
rpbId: "036t051384" -> HT016046758 -> 990176510200206441

---
almaMmsId: "99370697499206441" (CZ Titel statt NZ ZDB)
rpbId: "929t01044794" -> HT017427689 -> 990193391480206441

---
almaMmsId: "99370686789106441" (CZ Titel statt NZ ZDB)
rpbId: "929t01038436" -> HT016388625 -> 990180824070206441

---
almaMmsId: "99370686790306441" (CZ Titel statt NZ ZDB)
rpbId: "929t01038805" -> HT016515187 -> 990182143410206441


---
almaMmsId: "99370690340106441" (CZ Titel statt NZ ZDB)
rpbId: "929t01045608" -> HT017692163 -> 990197311930206441
```

But 5 mappings seem unclear to me, probably need help by @acka47 or @fsteeg  or RPB to identify the correct lobid record:

```
---
almaMmsId: "99370777663406441"
rpbId: "929t993448"  -> ist das die elektronische version? kann man elektronische Versionen in der RPB erkennen? Ich vermute, dass es die Printausgabe ist,
unter der almaMmsId is ein Consor CZ Titel.


---
almaMmsId: "99370693599306441"
rpbId: "036t980990" -> ist das die elektronische version? kann man elektronische Versionen in der RPB erkennen? Ich vermute, dass es die Printausgabe ist,
unter der almaMmsId is ein Consor CZ Titel.


---
almaMmsId: "990019846300106470"  -> Das schein ein lokaler Titel zu sein. Dürfte nicht zur RPB gehören.
hbzId: "HT017502667"

---
almaMmsId: "990000167930306443"  -> Das schein ein lokaler Titel zu sein. Dürfte nicht zur RPB gehören.
rpbId: "929t062907" -> HT006908366 -> 990054811920206441 (evtl dieser als Ersatz)


---
almaMmsId: "990027794510206443"  -> Das schein ein lokaler Titel zu sein. Dürfte nicht zur RPB gehören.
hbzId: "HT017502667" 
```

_Originally posted by @TobiasNx in https://github.com/hbz/lobid-resources/issues/2107#issuecomment-2531029471_

**Comment by TobiasNx** [comment]
Based on https://github.com/TobiasNx/metafacture_workflows/tree/master/getHbzIdFromLobid . The records resulted in 23 records that had not NZ ALMA MMS IDs:

```
NO NZ Record: 990000167930306443 -> NZ counterpart: 990054811920206441
NO NZ Record: 99370683064406441 -> NZ counterpart: 990174711090206441
NO NZ Record: 99370683584806441 -> NZ counterpart: 990188584160206441
NO NZ Record: 99370685222206441 -> NZ counterpart: 990227800790206441
NO NZ Record: 99370685802706441 -> NZ counterpart: 990181886860206441
NO NZ Record: 99370685807106441 -> NZ counterpart: 990133002700206441
NO NZ Record: 99370686223106441 -> NZ counterpart: 990178421190206441
NO NZ Record: 99370686223506441 -> NZ counterpart: 990173331820206441
NO NZ Record: 99370686737106441 -> NZ counterpart: 990173332420206441
NO NZ Record: 99370686789106441 -> NZ counterpart: 990180824070206441
NO NZ Record: 99370686790306441 -> NZ counterpart: 990182143410206441
NO NZ Record: 99370688114906441 -> NZ counterpart: 990179419420206441
NO NZ Record: 99370688470706441 -> NZ counterpart: 990176510200206441
NO NZ Record: 99370688948206441 -> NZ counterpart: 990214114060206441
NO NZ Record: 99370690340106441 -> NZ counterpart: 990197311930206441
NO NZ Record: 99370691768806441 -> NZ counterpart: 990170549260206441
NO NZ Record: 99370693599306441 -> NZ counterpart: 990159848000206441 (scheint die eigentliche Resource zu sein, das andere ist eine e resource die nicht in der zdb existiert)
NO NZ Record: 99370695565206441 -> NZ counterpart: 990197983170206441
NO NZ Record: 99370695975906441 -> NZ counterpart: 990188172110206441
NO NZ Record: 99370696004506441 -> NZ counterpart: 990192906610206441
NO NZ Record: 99370696006406441 -> NZ counterpart: 990193588700206441
NO NZ Record: 99370697499206441 -> NZ counterpart: 990193391480206441
NO NZ Record: 99370698952906441 -> NZ counterpart: 990165399670206441
NO NZ Record: 99370777663406441 -> NZ counterpart: 990191991310206441
```

Going to fix them in: 

Additionally 10 almaMmsIds that seem not to exist:

```
"Not found: 990105669680206441""; RPB Ressource 107t050923 existiert auch nicht
"Not found: 990111993150206441""; RPB Ressource 929t980468, korrekt wäre: 990057046840206441
"Not found: 990154003160206441""; RPB Ressource 107t073822, korrekt wäre: 990113928740206441
"Not found: 990194943290206441""; RPB Ressource 929t01072061 existiert auch nicht
"Not found: 990207162470206441""; RPB Ressource 929t01071437 existiert auch nicht
"Not found: 990207162570206441""; RPB Ressource 929t01071439  existiert auch nicht
"Not found: 990227492510206441""; RPB Ressource 929t01075755 existiert, ist kaiserslauthern webseite, aber die HT Nummer in den Daten existiert nicht und in lobid lässt sich auch nix dfinden
"Not found: 990227893900206441""; RPB Ressource 929t01077083 existiert, scheint eine edoweb resource zu sein, vermute: 99371268364806441
"Not found: 99370685827506441""; RPB Ressource 107t100197 existiert, ich vermute es ist: 990171910100206441
"Not found: 99371671391906441""; RPB Ressource 929t073746 existiert, ich vermute es ist: 990143552890206441
```

**Comment by acka47** [comment]
> is the `#983: HT018569020	RPB929t01074097` that you found in:
 https://github.com/hbz/rpb/issues/107#issuecomment-2633406615
the following resource: https://lobid.org/resources/990174232710206441

This is the RPB resource (from edoweb): https://rpb.lobid.org/929t01074097, so yes. Fixed with https://github.com/hbz/lookup-tables/commit/207a81f7179fb76504e8d8647e9ba1f11b55a2f2 .

**Comment by acka47** [comment]
> Additionally 10 almaMmsIds that seem not to exist:
>
> `"Not found: 990105669680206441""; RPB Ressource 107t050923 existiert auch nicht`

Deleted in c6f9125761c97167ebb80a9a84e6fe92de500766

> `"Not found: 990111993150206441""; RPB Ressource 929t980468, korrekt wäre: 990057046840206441`

Fixed in  c6f9125761c97167ebb80a9a84e6fe92de500766

`"Not found: 990154003160206441""; RPB Ressource 107t073822, korrekt wäre: 990113928740206441`

Hmm, I am not sure we should fix this. It might be better to remove it from the mapping and  inform RPB editors. Removed with c6f9125761c97167ebb80a9a84e6fe92de500766

`"Not found: 990194943290206441""; RPB Ressource 929t01072061 existiert auch nicht`

Removed with c6f9125761c97167ebb80a9a84e6fe92de500766

`"Not found: 990207162470206441""; RPB Ressource 929t01071437 existiert auch nicht`

Removed with c6f9125761c97167ebb80a9a84e6fe92de500766

`"Not found: 990207162570206441""; RPB Ressource 929t01071439  existiert auch nicht`

Removed with c6f9125761c97167ebb80a9a84e6fe92de500766

`"Not found: 990227492510206441""; RPB Ressource 929t01075755 existiert, ist kaiserslauthern webseite, aber die HT Nummer in den Daten existiert nicht und in lobid lässt sich auch nix dfinden`

Removed with c6f9125761c97167ebb80a9a84e6fe92de500766

`"Not found: 990227893900206441""; RPB Ressource 929t01077083 existiert, scheint eine edoweb resource zu sein, vermute: 99371268364806441`

Updated in c6f9125761c97167ebb80a9a84e6fe92de500766

`"Not found: 99370685827506441""; RPB Ressource 107t100197 existiert, ich vermute es ist: 990171910100206441`

Updated in c6f9125761c97167ebb80a9a84e6fe92de500766

`"Not found: 99371671391906441""; RPB Ressource 929t073746 existiert, ich vermute es ist: 990143552890206441`


Updated in c6f9125761c97167ebb80a9a84e6fe92de500766

**Comment by TobiasNx** [comment]
In context of https://github.com/hbz/lookup-tables/pull/63 I saw the following:

@acka47 I saw that the old lookup file has 4 records that had no rpbId in the old file. That are still missing an rpbId in the new version. How should I handle them?

https://github.com/hbz/lookup-tables/blob/51a6c6e1f709fdadd9d75a6b65f9661d4f121099/data/almaMmsId2rpbId.tsv?plain=1#L646
--> no matching rpb record

https://github.com/hbz/lookup-tables/blob/51a6c6e1f709fdadd9d75a6b65f9661d4f121099/data/almaMmsId2rpbId.tsv?plain=1#L2634
---> https://rpb.lbz-rlp.de/107t971213b3 ?

https://github.com/hbz/lookup-tables/blob/51a6c6e1f709fdadd9d75a6b65f9661d4f121099/data/almaMmsId2rpbId.tsv?plain=1#L3890
---> https://rpb.lbz-rlp.de/121t110028b1 ?

https://github.com/hbz/lookup-tables/blob/51a6c6e1f709fdadd9d75a6b65f9661d4f121099/data/almaMmsId2rpbId.tsv?plain=1#L3891
---> https://rpb.lbz-rlp.de/121t110028b2 ?

**Comment by acka47** [comment]
> I saw that the old lookup file has 4 records that had no rpbId in the old file. That are still missing an rpbId in the new version. How should I handle them?

Please just remove those lines.

**Comment by acka47** [comment]
Erledigt mit #61. Closing

**Comment by acka47** [comment]
Nochmal erledigt mit #64 . Closing again
